"""Generated Rust serde runtime metadata. Do not edit by hand."""

# 125 integer fields; 33 tagged-union payload fields.
STRUCT_INTEGER_FIELDS = {
    "ActivePosition": "#u64:app_token_wager_micros,payout_micros,wager_micros",
    "ActiveWithdrawalResponse": "#u64:amount_micros;i64:available_at_ms,created_at_ms",
    "BalanceOperationStatusResponse": "#u64:amount_micros;i64:available_at_ms",
    "EventMarket": "i32:display_probability_bps;u64:betting_closes_at_ms,created_at_ms,live_ends_at_ms,opened_at_ms,opens_at_ms,resolution_time_ms,resolved_at_ms,source_starts_at_ms",
    "FeeScheduleResponse": "u32:bonding_spot_fee_bps,parlay_fee_bps,shield_fee_multiplier,spot_fee_bps",
    "LegDetail": "i16:leg_index;i32:duration_secs;i64:window_start_ms;u64:market_id,resolution_time_ms",
    "MarketCurrentQuery": "u32:duration_secs",
    "MarketLookupQuery": "u32:duration_secs;u64:window_start_ms",
    "MarketMetadataEntry": "i64:betting_closes_at_ms,start_at_ms;u32:duration_secs;u64:market_id",
    "OrderLegJson": "u64:market_id",
    "PnlEventResponse": "#i64:cumulative_micros,pnl_micros;i64:resolved_at_ms",
    "PnlHistoryQuery": "i64:from_,to",
    "PnlHistoryScopedQuery": "i64:from_,to",
    "PortfolioStatsResponse": "#i64:total_pnl_micros;i32:losses,open_positions,total_positions,wins",
    "PositionDetailResponse": "#i64:app_token_wager_micros,net_payout_micros,payout_micros,pnl_micros,refunded_app_token_micros,wager_micros;i16:legs_count;i64:created_at_ms,resolved_at_ms",
    "PositionSummary": "#i64:app_token_wager_micros,net_payout_micros,payout_micros,pnl_micros,refunded_app_token_micros,wager_micros;i16:legs_count;i64:created_at_ms,resolved_at_ms",
    "PositionsByMarketsQuery": "u32:limit",
    "PositionsQuery": "u32:limit",
    "PriceStrikeMarket": "u64:betting_closes_at_ms,created_at_ms,open_strike_micros,opened_at_ms,resolution_time_ms,resolved_at_ms",
    "ProfileResponse": "i32:avatar_seed;i64:created_at_ms,updated_at_ms",
    "ProfitCapConfigResponse": "u64:default_max_profit_micros",
    "ProfitCapOverrideResponse": "u64:max_profit_micros",
    "PublicMarketsRawQuery": "u32:limit",
    "PublicReferralDepositMatchOffer": "#i64:match_limit_micros;i64:duration_ms",
    "PublicReferralInviterResponse": "i32:avatar_seed",
    "QueuedWithdrawalResponse": "#u64:amount_micros;i64:available_at_ms",
    "RecentResolutionEntry": "i64:resolved_at_ms,window_start_ms;u64:market_id",
    "RecentResolutionsQuery": "u32:duration_secs,limit",
    "RecentResolutionsResponse": "u32:duration_secs",
    "ReservedBalanceResponse": "#u64:reserved_micros",
    "RfqEstimateRequest": "u64:wager_micros",
    "RfqEstimateResponse": "u32:quotes_received;u64:fillable_micros,quoted_at_ms",
    "RfqResponse": "#u64:payout_micros;u32:quotes_received",
    "SessionResponse": "i64:deposit_chain_id;u64:expires_at",
    "SignedOrderJson": "u8:order_type;~u64:expires_at_ms,nonce,wager_micros",
    "TierFeeRate": "u32:parlay_fee_bps",
    "UserAvailableBalanceResponse": "#u64:available_micros,credited_custodial_deposit_micros,deposit_withdrawal_min_micros,pending_custodial_deposit_micros,withdrawal_max_micros",
    "UserDepositRequest": "u64:amount_micros",
    "UserDepositResponse": "#u64:amount_micros",
    "UserDepositWalletResponse": "i64:chain_id;u8:token_decimals",
    "UserTransactionResponse": "#i64:amount_micros;i64:available_at_ms,expires_at_ms,occurred_at_ms",
    "UserTransactionsRawQuery": "u32:limit",
    "UserWithdrawParams": "u64:amount_micros",
    "UserWithdrawResponse": "#u64:amount_micros;i64:available_at_ms",
    "UserWithdrawalStateResponse": "#u64:hold_threshold_micros,hold_trigger_amount_micros;i64:hold_duration_ms,hold_window_ms",
    "WalletAuthRequest": "u64:signed_at_ms",
}

STRUCT_REQUIRED_FIELDS = {
    "AccessResponse": "position_opening_allowed",
    "ActivePosition": "legs,payout_micros,position_id,role,status,wager_micros",
    "ActivePositionsResponse": "positions",
    "ActiveWithdrawalResponse": "amount_micros,created_at_ms,operation_id,withdrawal_stage",
    "BalanceOperationStatusResponse": "amount_micros,operation_id,status",
    "CancelResponse": "cancelled,message,request_id",
    "CheckHandleQuery": "handle",
    "CheckHandleResponse": "available",
    "ConfirmPositionQuery": "accept,position_id",
    "CreateRfqRequest": "order,use_app_tokens",
    "ErrorResponse": "code,error",
    "EventMarket": "betting_closes_at_ms,category_tags,created_at_ms,id,market_type,name,resolution_time_ms,status,tradeable,trading_channels",
    "FeeScheduleResponse": "bonding_spot_fee_bps,parlay_fee_bps,shield_fee_multiplier,spot_fee_bps,tiers,user_tier",
    "HandleAvailabilityQuery": "handle",
    "LegDetail": "direction,leg_index,market_id,outcome,resolution_time_ms",
    "MarketCurrentQuery": "asset,duration_secs",
    "MarketLookupQuery": "asset,duration_secs,window_start_ms",
    "MarketLookupResponse": "market",
    "MarketMetadataEntry": "asset,betting_closes_at_ms,duration_secs,market_id,start_at_ms",
    "MmRfqStatusResponse": "request_id,status",
    "OrderLegJson": "direction,market_id",
    "PnlEventResponse": "cumulative_micros,pnl_micros,resolved_at_ms,source",
    "PnlHistoryResponse": "events",
    "PortfolioStatsResponse": "losses,open_positions,total_pnl_micros,total_positions,win_rate_pct,wins",
    "PositionDetailResponse": "created_at_ms,id,legs,legs_count,legs_summary,payout_micros,status,wager_micros",
    "PositionSummary": "created_at_ms,has_binary_event_leg,id,legs_count,legs_summary,market_types,payout_micros,status,wager_micros",
    "PositionsByMarketsQuery": "market_ids",
    "PositionsByMarketsResponse": "positions",
    "PositionsListResponse": "partial,positions",
    "PreferencesResponse": "anonymous_mode_enabled,notifications_enabled,quote_tolerance",
    "PriceStrikeMarket": "betting_closes_at_ms,category_tags,created_at_ms,id,market_type,name,resolution_time_ms,status,tradeable,trading_channels",
    "ProfileResponse": "avatar_seed,created_at_ms,display_name,handle,updated_at_ms",
    "ProfitCapConfigResponse": "default_max_profit_micros,overrides",
    "ProfitCapOverrideResponse": "market_type,max_profit_micros",
    "PublicMarketResponse": "market",
    "PublicMarketsResponse": "markets",
    "PublicReferralCodeResponse": "status",
    "PublicReferralDepositMatchOffer": "duration_ms,match_limit_micros",
    "PublicReferralInviterResponse": "avatar_seed,display_name",
    "QueuedWithdrawalResponse": "amount_micros,available_at_ms,delivery_status,operation_id,submission_tx_hash,withdrawal_stage",
    "RecentResolutionEntry": "market_id,outcome,resolved_at_ms,window_start_ms",
    "RecentResolutionsQuery": "asset,duration_secs",
    "RecentResolutionsResponse": "asset,duration_secs,resolutions",
    "ReservedBalanceResponse": "reserved_micros",
    "RfqEstimateRequest": "legs,wager_micros",
    "RfqEstimateResponse": "quotable,quoted_at_ms,quotes_received,request_id",
    "RfqResponse": "quotes_received,request_id,status",
    "SessionResponse": "address,auth_wallet_address,expires_at,session_token,user_id",
    "SignedOrderJson": "expires_at_ms,legs,min_odds,nonce,shield_on,signature,user,wager_micros",
    "TierFeeRate": "parlay_fee_bps,tier",
    "UserAvailableBalanceResponse": "available_micros,credited_custodial_deposit_micros,deposit_withdrawal_min_micros,pending_custodial_deposit_micros,withdrawal_max_micros",
    "UserDepositRequest": "amount_micros,idempotency_key",
    "UserDepositResponse": "amount_micros,operation_id,tx_hash",
    "UserDepositWalletResponse": "address,chain_id,token_decimals,token_symbol",
    "UserTransactionResponse": "amount_micros,category,id,occurred_at_ms,status,title,unit",
    "UserTransactionsResponse": "items",
    "UserWithdrawParams": "amount_micros,idempotency_key",
    "UserWithdrawRequest": "authorization,withdraw_params",
    "UserWithdrawResponse": "amount_micros,operation_id,tx_hash",
    "UserWithdrawalStateResponse": "active_withdrawals,hold_duration_ms,hold_threshold_micros,hold_trigger_amount_micros,hold_window_ms,withdrawals_available",
    "WalletAuthRequest": "address,signature,signed_at_ms",
}

STRUCT_REQUIRED_NULLABLE_FIELDS = {
    "EventMarket": "opens_at_ms",
    "PositionDetailResponse": "net_payout_micros,pnl_micros,refunded_app_token_micros",
    "PositionSummary": "net_payout_micros,pnl_micros,refunded_app_token_micros",
}

TAGGED_UNION_FIELDS = {
    "ClientMessage": "Auth=;AuthResponse=signature:str,wallet_address:str;Pong=;Quote=data:str;Subscribe=protocol_version:u8,subscriptions:[]@RfqSubscription",
    "RfqSubscription": "All=;BinaryEvent=;PriceStrike=$@Asset",
    "ServerMessage": "AuthChallenge=challenge_id:str,timestamp_ms:u64;AuthResult=error:?str,session_token:?str,success:bool;Error=code:str,message:str;Ping=timestamp:u64;QuoteAck=accepted:bool,client_quote_id:?str,error:?str,quote_id:str,request_id:str;QuoteResult=client_quote_id:?str,fill_amount:?str,fill_odds:?u32,filled_at_ms:?u64,position_id:?str,quote_id:str,reason:?str,request_id:str,status:@QuoteResultStatus;RateLimit=retry_after_ms:u64;Rfq=data:str;Subscribed=protocol_version:u8",
    "WithdrawalAuthorization": "WalletSignature=signature:str,signed_at_ms:u64",
}

DENY_UNKNOWN_TAGGED_UNIONS = {
    "WithdrawalAuthorization",
}
